allowBuilds:
  core-js: false
  esbuild: false
minimumReleaseAgeExclude:
  - '@openai/codex-sdk@0.142.1'
  - '@openai/codex@0.142.1-darwin-arm64 || 0.142.1-darwin-x64 || 0.142.1-linux-arm64 || 0.142.1-linux-x64 || 0.142.1-win32-arm64 || 0.142.1-win32-x64 || 0.142.1'
