import type { IR } from './types'

// 写死的示例 IR：一张登录卡片。
// 结构：root(列) > card(列) > [标题, 邮箱输入, 密码输入, 登录按钮, 一行(链接×2)]
// 这个结构既有纵向列表（适合验证重排序），又有一个横向行（验证跨容器/换轴拖拽）。
export const sampleIR: IR = {
  rootId: 'root',
  nodes: {
    root: {
      id: 'root',
      type: 'frame',
      parentId: null,
      childIds: ['card', 'features', 'stats'],
      width: { mode: 'fill' }, // 画板宽由预览视口决定（视口驱动覆盖），不写固定值
      height: { mode: 'hug' },
      layout: { direction: 'col', gap: 24, padding: 24, align: 'center', justify: 'start' },
      style: { fill: '#f4f4f5' },
      props: {},
    },
    card: {
      id: 'card',
      type: 'frame',
      parentId: 'root',
      childIds: ['title', 'email', 'password', 'submit', 'links'],
      width: { mode: 'fill', max: 420 }, // fill 但封顶 420 → 宽屏居中(靠 root align center)、mobile 满宽
      height: { mode: 'hug' },
      layout: { direction: 'col', gap: 16, padding: 24, align: 'stretch', justify: 'start' },
      style: { fill: '#ffffff', radius: 16, borderColor: '#e4e4e7', borderWidth: 1, shadow: 2 },
      props: {},
    },
    title: {
      id: 'title',
      type: 'text',
      parentId: 'card',
      childIds: [],
      width: { mode: 'hug' },
      height: { mode: 'hug' },
      style: { color: '#18181b', fontSize: 24, fontWeight: 700 },
      props: { text: '登录账户' },
    },
    email: {
      id: 'email',
      type: 'input',
      parentId: 'card',
      childIds: [],
      width: { mode: 'fill' },
      height: { mode: 'fixed', value: 44 },
      style: { fill: '#ffffff', borderColor: '#d4d4d8', borderWidth: 1, radius: 8, color: '#71717a', fontSize: 14 },
      props: { placeholder: '邮箱' },
    },
    password: {
      id: 'password',
      type: 'input',
      parentId: 'card',
      childIds: [],
      width: { mode: 'fill' },
      height: { mode: 'fixed', value: 44 },
      style: { fill: '#ffffff', borderColor: '#d4d4d8', borderWidth: 1, radius: 8, color: '#71717a', fontSize: 14 },
      props: { placeholder: '密码' },
    },
    submit: {
      id: 'submit',
      type: 'button',
      parentId: 'card',
      childIds: [],
      width: { mode: 'fill' },
      height: { mode: 'fixed', value: 44 },
      style: { fill: '#4f46e5', color: '#ffffff', radius: 8, fontSize: 15, fontWeight: 600 },
      props: { text: '登录' },
    },
    links: {
      id: 'links',
      type: 'box',
      parentId: 'card',
      childIds: ['forgot', 'signup'],
      width: { mode: 'fill' },
      height: { mode: 'hug' },
      layout: { direction: 'row', gap: 8, padding: 0, align: 'center', justify: 'between' },
      style: {},
      props: {},
    },
    forgot: {
      id: 'forgot',
      type: 'text',
      parentId: 'links',
      childIds: [],
      width: { mode: 'hug' },
      height: { mode: 'hug' },
      style: { color: '#6366f1', fontSize: 13 },
      props: { text: '忘记密码？' },
    },
    signup: {
      id: 'signup',
      type: 'text',
      parentId: 'links',
      childIds: [],
      width: { mode: 'hug' },
      height: { mode: 'hug' },
      style: { color: '#6366f1', fontSize: 13 },
      props: { text: '注册' },
    },
    // —— 顶层横向区：两个固定宽列。固定宽之和 220+200+gap24 = 444：
    //    desktop(1280)/tablet(768) 横排；mobile(375) 触发 R1 塌成纵向（演示响应式）。
    features: {
      id: 'features',
      type: 'frame',
      parentId: 'root',
      childIds: ['colA', 'colB'],
      width: { mode: 'fill' },
      height: { mode: 'hug' },
      layout: { direction: 'row', gap: 24, padding: 0, align: 'stretch', justify: 'start' },
      style: {},
      props: {},
    },
    colA: {
      id: 'colA',
      type: 'box',
      parentId: 'features',
      childIds: ['colAText'],
      width: { mode: 'fixed', value: 220 },
      height: { mode: 'fixed', value: 120 },
      layout: { direction: 'col', gap: 0, padding: 16, align: 'start', justify: 'center' },
      style: { fill: '#e0e7ff', radius: 12 },
      props: {},
    },
    colAText: {
      id: 'colAText',
      type: 'text',
      parentId: 'colA',
      childIds: [],
      width: { mode: 'hug' },
      height: { mode: 'hug' },
      style: { color: '#3730a3', fontSize: 15, fontWeight: 600 },
      props: { text: '侧栏 A' },
    },
    colB: {
      id: 'colB',
      type: 'box',
      parentId: 'features',
      childIds: ['colBText'],
      width: { mode: 'fixed', value: 200 },
      height: { mode: 'fixed', value: 120 },
      layout: { direction: 'col', gap: 0, padding: 16, align: 'start', justify: 'center' },
      style: { fill: '#fce7f3', radius: 12 },
      props: {},
    },
    colBText: {
      id: 'colBText',
      type: 'text',
      parentId: 'colB',
      childIds: [],
      width: { mode: 'hug' },
      height: { mode: 'hug' },
      style: { color: '#9d174d', fontSize: 15, fontWeight: 600 },
      props: { text: '主区 B' },
    },
    // —— 第二个横向区：更宽的两列。固定宽之和 460+440+gap24 = 924：
    //    desktop(1280) 横排；tablet(768) 与 mobile(375) 均触发 R1 塌列。
    //    与 features(444，仅 mobile 塌) 配合，形成 desktop→tablet→mobile 渐进式响应。
    stats: {
      id: 'stats',
      type: 'frame',
      parentId: 'root',
      childIds: ['statA', 'statB'],
      width: { mode: 'fill' },
      height: { mode: 'hug' },
      layout: { direction: 'row', gap: 24, padding: 0, align: 'stretch', justify: 'start' },
      style: {},
      props: {},
    },
    statA: {
      id: 'statA',
      type: 'box',
      parentId: 'stats',
      childIds: [],
      width: { mode: 'fixed', value: 460 },
      height: { mode: 'fixed', value: 100 },
      layout: { direction: 'col', gap: 0, padding: 16, align: 'start', justify: 'center' },
      style: { fill: '#dcfce7', radius: 12 },
      props: {},
    },
    statB: {
      id: 'statB',
      type: 'box',
      parentId: 'stats',
      childIds: [],
      width: { mode: 'fixed', value: 440 },
      height: { mode: 'fixed', value: 100 },
      layout: { direction: 'col', gap: 0, padding: 16, align: 'start', justify: 'center' },
      style: { fill: '#fef9c3', radius: 12 },
      props: {},
    },
  },
}
